# -*- coding: utf-8 -*-
"""BinaryDDRBETAVAE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18lHgyUzYGqYXjQVRzTbiuAfuXRpl-myZ
"""

from google.colab import drive
drive.mount('/content/drive')
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc
)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

# Configuration
IMG_SIZE = (128, 128)
LATENT_DIM = 64
BATCH_SIZE = 32
DATA_ROOT = '/content/drive/MyDrive/ccps/datasets/binarydr'
CLASS_FOLDERS = ['0', '1']
NUM_CLASSES = len(CLASS_FOLDERS)
CLASS_COUNTS = {'0': 1825, '1': 1867}

def load_dataset():
    images, labels = [], []
    for class_idx, class_folder in enumerate(CLASS_FOLDERS):
        class_path = os.path.join(DATA_ROOT, class_folder)
        img_count = 0
        for img_name in os.listdir(class_path):
            if img_count >= CLASS_COUNTS[class_folder]:
                break
            img_path = os.path.join(class_path, img_name)
            img = load_img(img_path, target_size=IMG_SIZE)
            img_array = img_to_array(img) / 255.0
            images.append(img_array)
            labels.append(class_idx)
            img_count += 1
    images, labels = np.array(images), np.array(labels)
    indices = np.arange(len(images))
    np.random.shuffle(indices)
    images, labels = images[indices], labels[indices]
    split_idx = int(0.8 * len(images))
    x_train, y_train = images[:split_idx], labels[:split_idx]
    x_test, y_test = images[split_idx:], labels[split_idx:]
    print(f"Loaded dataset: {len(images)} images total")
    print(f"Train size: {len(x_train)}, Test size: {len(x_test)}")
    train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(BATCH_SIZE)
    test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(BATCH_SIZE)
    return train_ds, test_ds, x_test, y_test, images, labels

def unet_segmenter(input_size=(128, 128, 3)):
    inputs = Input(input_size)
    c1 = Conv2D(32, 3, activation='relu', padding='same')(inputs)
    c1 = BatchNormalization()(c1)
    p1 = MaxPooling2D()(c1)
    c2 = Conv2D(64, 3, activation='relu', padding='same')(p1)
    c2 = BatchNormalization()(c2)
    p2 = MaxPooling2D()(c2)
    c3 = Conv2D(128, 3, activation='relu', padding='same')(p2)
    c3 = BatchNormalization()(c3)
    u4 = Conv2DTranspose(64, 2, strides=2, padding='same')(c3)
    u4 = concatenate([u4, c2])
    c4 = Conv2D(64, 3, activation='relu', padding='same')(u4)
    c4 = BatchNormalization()(c4)
    u5 = Conv2DTranspose(32, 2, strides=2, padding='same')(c4)
    u5 = concatenate([u5, c1])
    c5 = Conv2D(32, 3, activation='relu', padding='same')(u5)
    c5 = BatchNormalization()(c5)
    outputs = Conv2D(1, 1, activation='sigmoid')(c5)
    return Model(inputs, outputs, name='UNet')

class Sampling(tf.keras.layers.Layer):
    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.random.normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

def build_vgg16_feature_extractor():
    vgg = tf.keras.applications.VGG16(include_top=False, weights='imagenet', input_shape=(128, 128, 3))
    vgg.trainable = False
    outputs = vgg.get_layer('block3_conv3').output
    model = tf.keras.Model(inputs=vgg.input, outputs=outputs)
    return model

def perceptual_loss(y_true, y_pred, feature_extractor):
    y_true = tf.image.resize(y_true, (128, 128))
    y_pred = tf.image.resize(y_pred, (128, 128))
    y_true = tf.keras.applications.vgg16.preprocess_input(y_true * 255.0)
    y_pred = tf.keras.applications.vgg16.preprocess_input(y_pred * 255.0)
    f_true = feature_extractor(y_true)
    f_pred = feature_extractor(y_pred)
    return tf.reduce_mean(tf.abs(f_true - f_pred))

def fft_loss(y_true, y_pred):
    y_true_fft = tf.signal.fft2d(tf.cast(y_true, tf.complex64))
    y_pred_fft = tf.signal.fft2d(tf.cast(y_pred, tf.complex64))
    return tf.reduce_mean(tf.abs(tf.abs(y_true_fft) - tf.abs(y_pred_fft)))

class VAE(tf.keras.Model):
    def __init__(self, latent_dim, beta=4.0, use_perceptual=False, use_fft=False):
        super().__init__()
        self.beta = beta
        self.use_perceptual = use_perceptual
        self.use_fft = use_fft
        self.encoder = self.build_encoder(latent_dim)
        self.decoder = self.build_decoder(latent_dim)
        self.total_loss_tracker = tf.keras.metrics.Mean(name='total_loss')
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(name='reconstruction_loss')
        self.kl_loss_tracker = tf.keras.metrics.Mean(name='kl_loss')
        if use_perceptual:
            self.feature_extractor = build_vgg16_feature_extractor()

    def build_encoder(self, latent_dim):
        inputs = Input(shape=(128, 128, 3))
        x = Conv2D(32, 3, activation='relu', strides=2, padding='same')(inputs)
        x = Conv2D(64, 3, activation='relu', strides=2, padding='same')(x)
        x = Flatten()(x)
        z_mean = Dense(latent_dim, name='z_mean')(x)
        z_log_var = Dense(latent_dim, name='z_log_var')(x)
        z = Sampling()([z_mean, z_log_var])
        return Model(inputs, [z_mean, z_log_var, z], name='encoder')

    def build_decoder(self, latent_dim):
        latent_inputs = Input(shape=(latent_dim,))
        x = Dense(32 * 32 * 32, activation='relu')(latent_inputs)
        x = Reshape((32, 32, 32))(x)
        x = Conv2DTranspose(64, 3, activation='relu', strides=2, padding='same')(x)
        x = Conv2DTranspose(32, 3, activation='relu', strides=2, padding='same')(x)
        outputs = Conv2DTranspose(3, 3, strides=(1, 1), padding='same', activation='tanh')(x)
        return Model(latent_inputs, outputs, name='decoder')

    def compile(self, optimizer):
        super().compile()
        self.optimizer = optimizer

    def train_step(self, data):
        if isinstance(data, tuple):
            data = data[0]
        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)
            reconstruction_loss = tf.reduce_mean(
                tf.reduce_sum(tf.keras.losses.binary_crossentropy(data, reconstruction), axis=(1, 2))
            )
            perc_loss, freq_loss = 0.0, 0.0
            if self.use_perceptual:
                perc_loss = perceptual_loss(data, reconstruction, self.feature_extractor)
            if self.use_fft:
                freq_loss = fft_loss(data, reconstruction)
            kl_loss = -0.5 * tf.reduce_mean(
                tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1)
            )
            total_loss = reconstruction_loss + self.beta * kl_loss + 0.1 * perc_loss + 0.1 * freq_loss
        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {
            'loss': self.total_loss_tracker.result(),
            'reconstruction_loss': self.reconstruction_loss_tracker.result(),
            'kl_loss': self.kl_loss_tracker.result(),
        }

class VAETrainer:
    def __init__(self, beta=4.0, use_perceptual=True, use_fft=True):
        self.vae = VAE(latent_dim=LATENT_DIM, beta=beta, use_perceptual=use_perceptual, use_fft=use_fft)
        self.train_losses = []

    def compute_accuracy_and_confusion(self, x, y_true):
        z_mean, z_log_var, z = self.vae.encoder(x)
        recon = self.vae.decoder(z).numpy()
        x_flat = recon.reshape((recon.shape[0], -1))
        clf = LogisticRegression(max_iter=1000)
        clf.fit(x_flat, y_true)
        y_pred = clf.predict(x_flat)
        acc = accuracy_score(y_true, y_pred)
        return acc, y_true, y_pred, clf, recon

    def train(self, train_ds, epochs=80):
        self.vae.compile(optimizer=tf.keras.optimizers.Adam(1e-4))
        for epoch in range(epochs):
            history = self.vae.fit(train_ds, epochs=1, verbose=1)
            loss = history.history['loss'][0]
            self.train_losses.append(loss)
            print(f"Epoch {epoch+1}/{epochs} - Loss: {loss:.4f}")
        # Plot training loss
        plt.plot(range(1, epochs+1), self.train_losses, label='Training Loss')
        plt.xlabel('Epoch')
        plt.ylabel('Loss')
        plt.title('Training Loss Over Epochs')
        plt.legend()
        plt.show()

def calculate_sensitivity_specificity(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    TP = cm[1, 1]
    TN = cm[0, 0]
    FP = cm[0, 1]
    FN = cm[1, 0]
    sensitivity = TP / (TP + FN) if (TP + FN) > 0 else 0
    specificity = TN / (TN + FP) if (TN + FP) > 0 else 0
    return sensitivity, specificity

def calculate_metrics(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='weighted')
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    sensitivity, specificity = calculate_sensitivity_specificity(y_true, y_pred)
    return {
        'Accuracy': accuracy,
        'F1 Score': f1,
        'Precision': precision,
        'Recall': recall,
        'Sensitivity': sensitivity,
        'Specificity': specificity
    }

def plot_fold_sens_spec(fold_metrics):
    sensitivities = [fm['Sensitivity'] for fm in fold_metrics]
    specificities = [fm['Specificity'] for fm in fold_metrics]
    folds = range(1, len(fold_metrics)+1)
    plt.plot(folds, sensitivities, marker='o', label='Sensitivity')
    plt.plot(folds, specificities, marker='s', label='Specificity')
    plt.xticks(folds)
    plt.xlabel('Fold')
    plt.ylabel('Score')
    plt.title('Sensitivity and Specificity Across Folds')
    plt.ylim(0, 1)
    plt.legend()
    plt.show()

def cross_val_metrics(trainer_class, x_all, y_all, n_splits=5, epochs=80):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    fold_metrics = []
    for fold, (train_index, test_index) in enumerate(skf.split(x_all, y_all), 1):
        print(f'\n=== Fold {fold} ===')
        x_train, x_test = x_all[train_index], x_all[test_index]
        y_train, y_test = y_all[train_index], y_all[test_index]
        trainer = trainer_class()
        train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(BATCH_SIZE)
        trainer.train(train_ds, epochs=epochs)
        acc, y_true, y_pred, clf, recon_test = trainer.compute_accuracy_and_confusion(x_test, y_test)
        metrics = calculate_metrics(y_true, y_pred)
        for k, v in metrics.items():
            print(f"{k}: {v:.4f}")
        fold_metrics.append(metrics)
        # Confusion matrix
        cm = confusion_matrix(y_true, y_pred)
        disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=CLASS_FOLDERS)
        fig, ax = plt.subplots(figsize=(5, 5))
        disp.plot(ax=ax, cmap='Blues', colorbar=False)
        plt.title(f'Fold {fold} Confusion Matrix')
        plt.show()
        # ROC Curve for the fold
        if hasattr(clf, "predict_proba"):
            y_score = clf.predict_proba(recon_test.reshape(len(y_true), -1))[:, 1]
            fpr, tpr, _ = roc_curve(y_true, y_score)
            roc_auc = auc(fpr, tpr)
            plt.plot(1-fpr, tpr, label='ROC (AUC = {:.2f})'.format(roc_auc))
            plt.xlabel('Specificity')
            plt.ylabel('Sensitivity')
            plt.title(f'ROC Curve Fold {fold}')
            plt.legend()
            plt.show()
    return fold_metrics

def summarize_metrics(fold_metrics):
    import numpy as np
    avg_metrics = {key: np.mean([fm[key] for fm in fold_metrics]) for key in fold_metrics[0].keys()}
    print('\n=== Average metrics across folds ===')
    for k, v in avg_metrics.items():
        print(f"{k}: {v:.4f}")
    # Table print
    print("\n| Fold | Accuracy | F1 Score | Precision | Recall | Sensitivity | Specificity |")
    print("|------|----------|----------|-----------|--------|-------------|-------------|")
    for i, fm in enumerate(fold_metrics, 1):
        print(f"| {i} | {fm['Accuracy']:.4f} | {fm['F1 Score']:.4f} | {fm['Precision']:.4f} | {fm['Recall']:.4f} | {fm['Sensitivity']:.4f} | {fm['Specificity']:.4f} |")
    print(f"| Avg | {avg_metrics['Accuracy']:.4f} | {avg_metrics['F1 Score']:.4f} | {avg_metrics['Precision']:.4f} | {avg_metrics['Recall']:.4f} | {avg_metrics['Sensitivity']:.4f} | {avg_metrics['Specificity']:.4f} |")
    return avg_metrics

if __name__ == "__main__":
    # Load all data
    _, _, _, _, x_all, y_all = load_dataset()
    print('\nStarting 5-fold cross-validation.')
    # Run CV (use fewer epochs per fold for speed)
    fold_metrics = cross_val_metrics(
        lambda: VAETrainer(beta=4.0, use_perceptual=True, use_fft=True),
        x_all, y_all, n_splits=5, epochs=80,
    )
    summarize_metrics(fold_metrics)
    plot_fold_sens_spec(fold_metrics)