# -*- coding: utf-8 -*-
"""DDRMULTIBETA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102tR1fu3ZK86Sk75c3YEejgNjppN9NT9
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import load_img, img_to_array, array_to_img
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, confusion_matrix, ConfusionMatrixDisplay,
    f1_score, precision_score, recall_score, roc_curve, auc
)
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import label_binarize

# SET MEMORY GROWTH FOR GPU
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except Exception as e:
        print("Could not set memory growth:", e)

IMG_SIZE = (128, 128)
LATENT_DIM = 64
BATCH_SIZE = 8
DATA_ROOT = '/content/drive/MyDrive/ccps/datasets/balancedmulti_drgrading'
SAVE_ROOT = '/content/drive/MyDrive/ccps/multidrgrading'
CLASS_FOLDERS = ['0', '1', '2', '3', '4']
NUM_CLASSES = len(CLASS_FOLDERS)

def load_dataset():
    images, labels, names = [], [], []
    for class_idx, class_folder in enumerate(CLASS_FOLDERS):
        class_path = os.path.join(DATA_ROOT, class_folder)
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            img = load_img(img_path, target_size=IMG_SIZE)
            img_array = img_to_array(img) / 255.0
            images.append(img_array)
            labels.append(class_idx)
            names.append(img_name)
    images, labels, names = np.array(images), np.array(labels), np.array(names)
    indices = np.arange(len(images))
    np.random.shuffle(indices)
    images, labels, names = images[indices], labels[indices], names[indices]
    split_idx = int(0.8 * len(images))
    x_train, y_train, names_train = images[:split_idx], labels[:split_idx], names[:split_idx]
    x_test, y_test, names_test = images[split_idx:], labels[split_idx:], names[split_idx:]
    train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(BATCH_SIZE)
    test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(BATCH_SIZE)
    return train_ds, test_ds, x_test, y_test, images, labels, names, names_test

def unet_segmenter(input_size=(128, 128, 3)):
    inputs = Input(input_size)
    c1 = Conv2D(32, 3, activation='relu', padding='same')(inputs)
    c1 = BatchNormalization()(c1)
    p1 = MaxPooling2D()(c1)
    c2 = Conv2D(64, 3, activation='relu', padding='same')(p1)
    c2 = BatchNormalization()(c2)
    p2 = MaxPooling2D()(c2)
    c3 = Conv2D(128, 3, activation='relu', padding='same')(p2)
    c3 = BatchNormalization()(c3)
    u4 = Conv2DTranspose(64, 2, strides=2, padding='same')(c3)
    u4 = concatenate([u4, c2])
    c4 = Conv2D(64, 3, activation='relu', padding='same')(u4)
    c4 = BatchNormalization()(c4)
    u5 = Conv2DTranspose(32, 2, strides=2, padding='same')(c4)
    u5 = concatenate([u5, c1])
    c5 = Conv2D(32, 3, activation='relu', padding='same')(u5)
    c5 = BatchNormalization()(c5)
    outputs = Conv2D(1, 1, activation='sigmoid')(c5)
    return Model(inputs, outputs, name='UNet')

class Sampling(tf.keras.layers.Layer):
    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.random.normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

class VAE(tf.keras.Model):
    def __init__(self, latent_dim, beta=4.0):
        super().__init__()
        self.encoder = self.build_encoder(latent_dim)
        self.decoder = self.build_decoder(latent_dim)
        self.total_loss_tracker = tf.keras.metrics.Mean(name='total_loss')
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(name='reconstruction_loss')
        self.kl_loss_tracker = tf.keras.metrics.Mean(name='kl_loss')
        self.beta = beta

    def build_encoder(self, latent_dim):
        inputs = Input(shape=(128, 128, 3))
        x = Conv2D(32, 3, activation='relu', strides=2, padding='same')(inputs)
        x = Conv2D(64, 3, activation='relu', strides=2, padding='same')(x)
        x = Flatten()(x)
        z_mean = Dense(latent_dim, name='z_mean')(x)
        z_log_var = Dense(latent_dim, name='z_log_var')(x)
        z = Sampling()([z_mean, z_log_var])
        return Model(inputs, [z_mean, z_log_var, z], name='encoder')

    def build_decoder(self, latent_dim):
        latent_inputs = Input(shape=(latent_dim,))
        x = Dense(32 * 32 * 32, activation='relu')(latent_inputs)
        x = Reshape((32, 32, 32))(x)
        x = Conv2DTranspose(64, 3, activation='relu', strides=2, padding='same')(x)
        x = Conv2DTranspose(32, 3, activation='relu', strides=2, padding='same')(x)
        outputs = Conv2DTranspose(3, 3, activation='sigmoid', padding='same')(x)
        return Model(latent_inputs, outputs, name='decoder')

    def compile(self, optimizer):
        super().compile()
        self.optimizer = optimizer

    def train_step(self, data):
        if isinstance(data, tuple): data = data[0]
        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)
            reconstruction_loss = tf.reduce_mean(tf.reduce_sum(tf.keras.losses.binary_crossentropy(data, reconstruction), axis=(1, 2)))
            kl_loss = -0.5 * tf.reduce_mean(tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1))
            perc_loss = 0.0
            freq_loss = 0.0
            total_loss = reconstruction_loss + self.beta * kl_loss + 0.1 * perc_loss + 0.1 * freq_loss
        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {'loss': self.total_loss_tracker.result(),
                'reconstruction_loss': self.reconstruction_loss_tracker.result(),
                'kl_loss': self.kl_loss_tracker.result()}

class VAETrainer:
    def __init__(self):
        self.vae = VAE(latent_dim=LATENT_DIM)
        self.train_losses = []
        self.segmenter = unet_segmenter(input_size=(128, 128, 3))

    def compute_accuracy_and_preds(self, x, y_true, batch_size=32):
        z_means, z_log_vars, zs, recons = [], [], [], []
        for i in range(0, len(x), batch_size):
            xb = x[i:i+batch_size]
            z_mean, z_log_var, z = self.vae.encoder(xb)
            recon = self.vae.decoder(z).numpy()
            z_means.append(z_mean.numpy())
            z_log_vars.append(z_log_var.numpy())
            zs.append(z.numpy())
            recons.append(recon)
            tf.keras.backend.clear_session()
        z = np.concatenate(zs, axis=0)
        recon = np.concatenate(recons, axis=0)

        x_flat = recon.reshape((recon.shape[0], -1))
        clf = LogisticRegression(max_iter=1000, multi_class='multinomial')
        clf.fit(x_flat, y_true)
        y_pred = clf.predict(x_flat)

        acc = accuracy_score(y_true, y_pred)
        f1 = f1_score(y_true, y_pred, average='macro')
        precision = precision_score(y_true, y_pred, average='macro')
        recall = recall_score(y_true, y_pred, average='macro')
        sensitivity = recall

        cm = confusion_matrix(y_true, y_pred)
        specificity_list = []
        for i in range(len(cm)):
            TP = cm[i, i]
            FP = cm[:, i].sum() - TP
            FN = cm[i, :].sum() - TP
            TN = cm.sum() - (TP + FP + FN)
            specificity = TN / (TN + FP + 1e-7)
            specificity_list.append(specificity)
        specificity = np.mean(specificity_list)

        y_true_bin = label_binarize(y_true, classes=list(range(NUM_CLASSES)))
        y_score = clf.predict_proba(x_flat)
        fpr, tpr, _ = roc_curve(y_true_bin.ravel(), y_score.ravel())
        roc_auc = auc(fpr, tpr)

        plt.figure()
        plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.4f})')
        plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        plt.title('Receiver Operating Characteristic')
        plt.legend(loc='lower right')
        plt.grid(True)
        plt.show()

        return acc, y_pred, f1, precision, recall, sensitivity, specificity

    def train_and_save(self):
        train_ds, test_ds, x_test, y_test, x_all, y_all, names_all, names_test = load_dataset()
        self.vae.compile(optimizer=tf.keras.optimizers.Adam(1e-4))

        epochs = 30
        for epoch in range(epochs):
            tf.keras.backend.clear_session()
            history = self.vae.fit(train_ds, epochs=1, verbose=1)
            loss = history.history['loss'][0]
            self.train_losses.append(loss)
            print(f"Epoch {epoch+1}/{epochs} - Loss: {loss:.4f}")

        acc, y_pred, f1, prec, rec, sens, spec = self.compute_accuracy_and_preds(x_test, y_test)

        print("\nEvaluation Metrics:")
        print(f"Accuracy     : {acc:.4f}")
        print(f"F1 Score     : {f1:.4f}")
        print(f"Precision    : {prec:.4f}")
        print(f"Recall       : {rec:.4f}")
        print(f"Sensitivity  : {sens:.4f}")
        print(f"Specificity  : {spec:.4f}")

        cm = confusion_matrix(y_test, y_pred)
        disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=CLASS_FOLDERS)
        disp.plot(cmap=plt.cm.Blues)
        plt.title('Confusion Matrix')
        plt.show()

        plt.figure(figsize=(8, 5))
        plt.plot(range(1, epochs+1), self.train_losses, label='Training Loss')
        plt.xlabel('Epoch')
        plt.ylabel('Loss')
        plt.title('Training Loss Over Epochs')
        plt.legend()
        plt.show()

if __name__ == "__main__":
    trainer = VAETrainer()
    trainer.train_and_save()